### ISSUE TITLE
Add a map

### ISSUE THREAD

**Issue by soggybag** [soggybag/sf-public-spaces#4]
It would be great to show a map. This would probably work best on the detail page. 

Probably Google maps is the best choice. 

There are many React Components on npm that do this. Here is a link to one: 

- https://github.com/google-map-react/google-map-react

You can get the geo location data from `const { title, imageSrc, desc } = props.location.state`. You'll need to `geo` here. Take a look at `src/project-date.js`.

NOTE! Currently the geo coordinates are not correct in the `project-data.js`. You can update the values here or just realize that the locations will not be correct until these are updated.

**Comment by dominnovak** [comment]
Hello there, I would like to solve this issue. Can you assign it to me?

**Comment by soggybag** [comment]
Closed thanks!
